name: augment_zero
description: An Augmented-Reality app for a hackathon.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  arcore_flutter_plugin: ^0.0.5+1
  sensors: ^0.4.2+4
  torch_compat: ^1.0.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
